### ISSUE TITLE
Live Playback Latency

### ISSUE THREAD

**Issue by priyankjain12** [ashfaq1701/fast-mixer#7]
Hi, Thanks for the great work.

Is there any way to reduce the delay between the recorded voice and its playback. currently, when I record and enabled the live playback there is a delay in the playback of voice. It's not instant. So is there any way to reduce that delay?

**Comment by ashfaq1701** [comment]
Hi @priyankjain12 ! Thank you very much for showing interest in this project :) I know about the delay. I tried to minimise it in several ways. One of such was by decreasing the sample size in live playback callback. For me it resulted in the same outcome. But you can try decreasing the sample size (if you want). I have bigger scope in mind for this project and currently working on an interactive audio visualizer and selector for recorded audio files. After that part and noise cancellation using Digital Signal Processing filter kernel I will return to performance optimizations like this issue (in a month). I have plan to solve it even if it is necessary by making change in oboe. :) 

Again thanks for your appreciation.
